### PR TITLE
Added https://ieeexplore.ieee.org/stamp/stamp.jsp?arnumber=9893129

### PR DESCRIPTION
**Pull request by LongquanJiang**

### CODE REVIEW

**Review by xixi019 — COMMENTED** [review]
In leaderboard for QALD-7, the Accuracy, Language and reported by blank are wrongly filled. And gAnswer2 are repported twice by same values, maybe we should delete them

**Review by xixi019 — COMMENTED** [review]
Also, do not forget to add the model to systems table.

**Comment by RicardoUsbeck** [comment]
Merge Conflict? If solved, what does that close?

**Review by xixi019 — COMMENTED** [review]
seems good to me, there are still some models being reported a few times with same scores. I will open a pull request and edit that later.

**Comment by xixi019** [comment]
> Merge Conflict? If solved, what does that close?

you mean #70 ?  @LongquanJiang  seems liek there's no commit there

**Comment by RicardoUsbeck** [comment]
I mean this:

**Pull request closed without merging**
