### PR TITLE
Create Mintaka.md

### PR DESCRIPTION
**Pull request by huntila**
Paper source: https://aclanthology.org/2022.coling-1.138

### CODE REVIEW

**Comment by xixi019** [comment]
also add entry in the https://github.com/KGQA/leaderboard/blob/gh-pages/README.md page
And tell me or @LongquanJiang to review it once you committed the change 
thank you for the request! :)

**Comment by xixi019** [comment]
close #79

**Comment by LongquanJiang** [comment]
I think some results are missing, like for KGQA models. Please added them. @huntila  huntila

**Review by xixi019 — CHANGES_REQUESTED** [review]
Combine the language model, kgqa models and retriever-reader mode into one. I think we could even combine the multilingual one, what do you think @LongquanJiang

**Pull request merged**
