### PR TITLE
add test score, dataset and system description from https://ieeexplore.ieee.org/stamp/stamp.jsp?arnumber=9834917 and https://journals.riverpublishers.com/index.php/JWE/article/view/11463

### LINKED ISSUE #55: Add https://ieeexplore.ieee.org/stamp/stamp.jsp?arnumber=9834917

### LINKED ISSUE #56: Add https://journals.riverpublishers.com/index.php/JWE/article/view/11463

### PR DESCRIPTION
**Pull request by xixi019**
close #55 close #56

### CODE REVIEW

**Review by LongquanJiang — COMMENTED** [review]
@RicardoUsbeck @xixi019 
I am not sure if we also need to track the accuracy performance, at least in the initial stage of the leaderboard, we did not consider accuracy on LC-QuAD datasets. Also, few existing systems are evaluated in terms of accuracy.

**Comment by RicardoUsbeck** [comment]
If we have it now anyway, we keep it but we should focus on F1/QALD-F1/P/R. What do you think?

**Comment by LongquanJiang** [comment]
Yes, we can keep it and put accuracy numbers in a new column, should not mix up with F1 scores, and sort them by F1 score

**Comment by LongquanJiang** [comment]
Furthermore, different KGQA datasets have their own main metrics, just like P/R/F1 for QALD and LC-QuAD. Hit@1 for WebQSP. We should focus on their own metrics, keep track of them and sort them. if some works evaluate with another metric, if necessary, we can also keep them, but put them in a new column.

**Comment by xixi019** [comment]
Add accuracy column, check the commits  :p @LongquanJiang

**Pull request merged**
